### ISSUE TITLE
MAJOR ISSUE

### ISSUE THREAD

**Issue by mribby786123** [prabhakar267/WA-Reader#10]
i dont know wether its because of a new whatsapp update but ur reader doesnt seem to work for me. it always says invalid text file or something on the lines.

my original file was really long so i thought that was the reason but then i edited it and made it really short, probably about 5 strands of conversation 

please help and please fix asap!!

**Comment by prabhakar267** [comment]
@mribby786123 if you could provide me with the text file, then i will be able to resolve the issue better.

**Comment by mribby786123** [comment]
[_chat.txt](https://github.com/prabhakar267/whatsapp-reader/files/1049754/_chat.txt)

**Comment by mribby786123** [comment]
@prabhakar267

**Comment by prabhakar267** [comment]
@mribby786123 I am working on your issue
If you could tell me what phone did you use for converting your chat to text file?

**Comment by mribby786123** [comment]
Iphone 5s

**Comment by mribby786123** [comment]
Have you resolved the issue yet my friend?

**Comment by mribby786123** [comment]
@prabhakar267

**Comment by frankgilcrest** [comment]
He won't fix your issue because he is running a scam. He stores your chats and tells you he isn't. I caught him in the act and said it was a "bug" in his code. There were chats from years ago there. He is probably using people's data or giving it to other people to run extortion scams. Do not send anything to this person!!!

**Comment by mribby786123** [comment]
Lol i got nothing to hide. If he is trying to do something dodgy he cant do shit

**Comment by prabhakar267** [comment]
@mribby786123 I am working on your issue. It takes time to resolve a timestamp issue. If you want  I can easily stop working on it since I have a lot of better things to do than reading to a "fake" account abusing me and the hard work I put in behind those.

**Comment by mribby786123** [comment]
@prabhakar267 please carry on fixing the issue. I appreciate it

**Comment by prabhakar267** [comment]
@mribby786123 I have updated the code and did a lot of refactoring :smile:
Kindly check the updated link https://whatsapp-reader.herokuapp.com/

Feel free to open the issue again if you face the same problem again

**Comment by mribby786123** [comment]
"It wasn't a valid text file or we were not able to convert it" still not working

**Comment by mribby786123** [comment]
not working my friend, the same message keeps popping up
